// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxeoektwknldwkrdchhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZW9la3R3a25sZHdrcmRjaGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzIxMzUsImV4cCI6MjA1OTIwODEzNX0.khwBGGFpOwSXu2-ku1bMrK1SusHlx47XPyTUa3vYKA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);